name: Continuous Delivery

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: push

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@722adc6
      - uses: actions/setup-node@1c5c137
        with:
          node-version: 14.x
      - uses: actions/cache@70655ec
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --ignore-scripts
        name: Install dependencies
      - run: yarn build
        name: Build package

      # Continuous Delivery Pipeline --

      - id: short-sha1
        name: Get short Git SHA-1
        run: echo "::set-output name=value::$(echo $GITHUB_SHA | cut -c1-8)"
      - uses: codfish/semantic-release-action@a313b22
        name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@24cf9bd
        name: Get Latest Tag
      - id: latest-version
        uses: frabert/replace-string-action@4ec615c
        name: Format Latest Tag to Version
        with:
          pattern: '^v?(.+)'
          string: "${{ steps.latest-tag.outputs.tag }}"
          replace-with: '$1'
      - id: sentry-release
        name: Generate Sentry Release ID
        run: echo "::set-output name=id::${{ env.SERVICE_NAME }}@${{ steps.latest-version.outputs.replaced }}-${{ steps.short-sha1.outputs.value }}"
      - uses: tclindner/sentry-releases-action@658b2f3
        name: Publish the release to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: chiffre
          SENTRY_PROJECT: push
        with:
          tagName: ${{ steps.sentry-release.outputs.id }}
          environment: production
      - uses: 47ng/actions-clever-cloud@master
        name: Deploy to Clever Cloud
        with:
          alias: push
          timeout: 600
          extraEnvSafelist: SENTRY_RELEASE
          CLEVER_ENV_SENTRY_RELEASE: ${{ steps.sentry-release.outputs.id }}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
